### ISSUE TITLE
Fails to compile on Cent 6.5

### ISSUE THREAD

**Issue by spuder** [Pithikos/docker-enter#1]
Attempting to compile on CentOS gives the following error:

```
[root@foobar docker-enter]# yum install gcc gcc-c++
[root@foobar docker-enter]# gcc docker-enter.c -o docker-enter
/tmp/ccV4P95v.o: In function `open_namespace':
docker-enter.c:(.text+0x4d9): undefin
```

According to this stack overflow question, you need to use g++, however that also fails. 
http://stackoverflow.com/questions/4222501/how-to-solve-collect2-ld-returned-1-exit-status

```
[root@foobar docker-enter]# g++ docker-enter.c -o docker-enter
docker-enter.c:8:1: warning: "_GNU_SOURCE" redefined
<command-line>: warning: this is the location of the previous definition
docker-enter.c: In function ‘void open_namespace(char*)’:
docker-enter.c:211: error: ‘setns’ was not declared in this scope
docker-enter.c: In function ‘int main(int, char**)’:
docker-enter.c:231: warning: deprecated conversion from string constant to ‘char*’
docker-enter.c:232: warning: deprecated conversion from string constant to ‘char*’
docker-enter.c:233: warning: deprecated conversion from string constant to ‘char*’
docker-enter.c:234: warning: deprecated conversion from string constant to ‘char*’
docker-enter.c:235: warning: deprecated conversion from string constant to ‘char*’
```

```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

$ g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
```

**Comment by Pithikos** [comment]
You don't need C++. The codebase is simple C.

I tested compiling in a CentOS container and it works fine:

```
manos@manos-530U3C:~$ sudo docker run -it centos bash
[root@781c22602417 /]# yum install gcc
[root@781c22602417 /]# yum install git
[root@781c22602417 /]# git clone https://github.com/Pithikos/docker-enter.git
[root@781c22602417 /]# cd docker-enter
[root@781c22602417 docker-enter]# gcc docker-enter.c -o docker-enter
[root@781c22602417 docker-enter]# ./docker-enter 
No container ID given. Use -h for help
```

What kernel version do you have? (`uname -a`)

**Comment by Pithikos** [comment]
Also.. is the last error line correct? Namely `docker-enter.c:(.text+0x4d9): undefin`? Strikes me as very strange that you get "undefin".

**Comment by spuder** [comment]
The undefin is a copy and paste error. 

By changing `docker run -it centos bash` to `docker run -it centos:centos6 bash` I can reproduce this. (since `centos` is an alias for `centos:latest` which is centos 7). 

```
docker run -it --name='test' centos:centos6 /bin/bash
yum install gcc git
git clone https://github.com/Pithikos/docker-enter.git
cd docker-enter/
gcc docker-enter.c -o docker-enter
/tmp/ccyeV1s2.o: In function `open_namespace':
docker-enter.c:(.text+0x4d9): undefined reference to `setns'
collect2: ld returned 1 exit status
```

**Comment by Pithikos** [comment]
The thing is that the whole docker-enter thing makes usage of the `setns` system call. This system call is kind of new and as I saw, Centos6 is really old.. 2011. My guess is that either the kernel you have or the system libraries are too old. Why not just update to Centos7?

The strange thing is how you got Docker running on such an old system. I guess it uses it own way to create containers and not Linux-containers.

`setns` can be found in `sched.h` if your system supports it. On my Ubuntu:

```
manos@box:~$ sudo find / -name "sched.h" -exec cat {} \; | grep setns
extern int setns (int __fd, int __nstype) __THROW;
extern int setns (int __fd, int __nstype) __THROW;
..
```
